import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        tertiary: '#a4d393',
        'on-primary': '#1d352f',
        'on-tertiary-fixed': '#022100',
        'inverse-on-surface': '#313030',
        'error-container': '#93000a',
        surface: '#131313',
        'on-primary-container': '#6f8981',
        'secondary-fixed': '#ffe088',
        primary: '#b1ccc4',
        'primary-fixed-dim': '#b1ccc4',
        'on-error': '#690005',
        'on-surface-variant': '#c1c8c5',
        'inverse-surface': '#e5e2e1',
        'surface-tint': '#b1ccc4',
        error: '#ffb4ab',
        outline: '#8c928f',
        'secondary-fixed-dim': '#e9c349',
        'secondary-container': '#af8d11',
        'inverse-primary': '#4b635d',
        'on-primary-fixed': '#06201b',
        'on-surface': '#e5e2e1',
        'on-secondary-container': '#342800',
        'surface-container': '#201f1f',
        'on-tertiary-container': '#638f55',
        secondary: '#e9c349',
        'outline-variant': '#424846',
        'tertiary-fixed': '#c0f0ad',
        'on-background': '#e5e2e1',
        'tertiary-fixed-dim': '#a4d393',
        'tertiary-container': '#022100',
        'on-primary-fixed-variant': '#334b45',
        'primary-fixed': '#cde8e0',
        'on-secondary-fixed-variant': '#574500',
        'surface-container-highest': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-fixed-variant': '#28501e',
        'on-error-container': '#ffdad6',
        'surface-bright': '#393939',
        'surface-container-high': '#2a2a2a',
        'on-secondary': '#3c2f00',
        'on-tertiary': '#113809',
        'surface-container-low': '#1c1b1b',
        'surface-dim': '#131313',
        'on-secondary-fixed': '#241a00',
        'surface-variant': '#353534',
        'primary-container': '#061f1a',
      },
      spacing: {
        'margin-mobile': '1.25rem',
        'stack-lg': '2rem',
        gutter: '1rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'margin-desktop': '2.5rem',
      },
      fontFamily: {
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg': ['var(--font-libre-caslon)', 'Libre Caslon Text', 'serif'],
        'label-caps': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'title-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-libre-caslon)', 'Libre Caslon Text', 'serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-lg': ['var(--font-libre-caslon)', 'Libre Caslon Text', 'serif'],
        sans: ['var(--font-inter)', 'Inter', 'sans-serif'],
        arabic: ['var(--font-amiri)', 'serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
